import jsPDF from "jspdf";
import { theme } from "./theme";

export function addFooter(
  pdf: jsPDF,
  page: number,
  totalPages: number
) {
  const pageHeight = pdf.internal.pageSize.getHeight();
  const pageWidth = pdf.internal.pageSize.getWidth();

  pdf.setDrawColor(220);

  pdf.line(
    theme.margin,
    pageHeight - 18,
    pageWidth - theme.margin,
    pageHeight - 18
  );

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(9);
  pdf.setTextColor(theme.gray);

  pdf.text(
    "Generated by PagePulse",
    theme.margin,
    pageHeight - 10
  );

  pdf.text(
    `Page ${page} of ${totalPages}`,
    pageWidth - theme.margin,
    pageHeight - 10,
    {
      align: "right",
    }
  );
}