import type { AuditReport } from "../types/audit";

export function buildReportSummary(report: AuditReport) {
  return `
Website Audit

Title: ${report.title}

HTTP Status: ${report.http_status}

Response Time: ${report.response_time_ms} ms

H1 Count: ${report.h1_count}

Word Count: ${report.word_count}

Missing ALT Images: ${report.images_missing_alt}

Meta Description:
${report.meta_description || "Not Found"}

Generated by PagePulse
`.trim();
}